<a href="https://colab.research.google.com/github/JeetDodiy/panda-data/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Start Panda

In [ ]:
import numpy as np
import pandas as pd

#Series in Panda

In [ ]:
label = ['A','B','C']
my_list = [10,20,30]
arr = np.array([10,20,30])
dist = {'1':10,'2':20,'3':30}

In [ ]:
pd.Series(dist)

1    10
2    20
3    30
dtype: int64

In [ ]:
pd.Series(my_list,index=label)

A    10
B    20
C    30
dtype: int64

# **Data Freme**

***Create data frema***